In [2]:
# import imageio
# import scipy.ndimage as ndi
import cv2
import numpy as np
import math

In [5]:
img = cv2.imread('img05.png')

frame_normalized = img.astype(np.float32) / 255.0
img2 = cv2.cvtColor(frame_normalized, cv2.COLOR_BGR2GRAY)

stats = cv2.meanStdDev(img2)
mean, std = stats
print(mean, std)

d_im = 4*std

print("diff = ",d_im)

tau = 1

g_img = 2 if d_im > 1/tau else 1

print(g_img)

if g_img == 1:
    gamma = -math.log(std, 2)
    
elif g_img == 2:
    gamma = math.exp((1-(mean + std))/2)

print(gamma)

gam_img = np.power(frame_normalized, gamma)
k = gam_img + (1-gam_img)*(mean**gamma)

print('kay', k)

heaviside = 1 if (0.5-mean) > 0 else 0
c = 1/(1 + heaviside*(k-1))

print('yay', c)

img_out = c * np.power(frame_normalized, gamma)

print('Semifinal',img_out)

frame_scaled = (img_out * 255.0).astype(np.uint8)


# frame_scaled
cv2.imshow('output', frame_scaled)
cv2.imwrite('kang.jpg',frame_scaled)

# for i in range(10000):
#     print(i, end = '\r') 
    
# # img.release()
# cv2.destroyAllWindows()

[[0.36796715]] [[0.21783186]]
diff =  [[0.87132745]]
1
2.1987130955957346
kay [[[0.17308777 0.20325657 0.13061721]
  [0.17308777 0.20325657 0.13061721]
  [0.17308777 0.20325657 0.13061721]
  ...
  [0.18836937 0.23213632 0.14792326]
  [0.18836937 0.23213632 0.14792326]
  [0.18836937 0.23213632 0.14792326]]

 [[0.16782657 0.19670147 0.12785665]
  [0.16782657 0.19670147 0.12785665]
  [0.1695521  0.19885725 0.1287515 ]
  ...
  [0.18836937 0.23213632 0.14792326]
  [0.18836937 0.23213632 0.14792326]
  [0.18836937 0.23213632 0.14792326]]

 [[0.16120474 0.18437697 0.12698698]
  [0.16120474 0.18437697 0.12698698]
  [0.16445976 0.18836937 0.1287515 ]
  ...
  [0.18836937 0.23213632 0.14792326]
  [0.18836937 0.23213632 0.14792326]
  [0.18836937 0.23213632 0.14792326]]

 ...

 [[0.25663403 0.25663403 0.16120474]
  [0.25663403 0.25663403 0.16120474]
  [0.25663403 0.25663403 0.16120474]
  ...
  [0.11133191 0.1215939  0.1115738 ]
  [0.11133191 0.1215939  0.1115738 ]
  [0.1114438  0.12229082 0.11172234

True